spring:
#  数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    userName : root
    password : 123456
    url : jdbc:mysql://127.0.0.1/sell_new?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql : true
    open-in-view: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379

server:
  servlet:
    context-path:
      /sell

wechat:
  mpAppId: wx0452d6d413512071
  mpAppSecret: 6f0782b05224b5ffb3eef11ed0aea822

#后台服务器地址
project-url:
  wechatMpAuthorize: http://eennxw.natappfree.cc

